### ISSUE TITLE
nes6502: Instr. 02 (JAM)

### ISSUE THREAD

**Issue by L-Spiro** [SingleStepTests/65x02#1]
According to Visual6502, behavior differs between hardware and these tests:
![image](https://github.com/SingleStepTests/65x02/assets/7362666/caf8df74-2f81-4c6e-b6f2-ed9342823952)
(Note that it is calling the instruction `ASL` but it is `JAM`/`KIL`.)

This is the process used by these JSON tests (in half-cycles):
```
1.1 Copy DataBus -> OpCode;
1.2 Read PC+1 Discard.
2.1
2.2 Read PC+1 Discard. Repeat this cycle forever.
```

This should apply to all `JAM` opcodes.

**Comment by TomHarte** [comment]
I think this was also reported in the old repository as [6502 02 58 f3 case doesn't match Visual 6502](https://github.com/SingleStepTests/ProcessorTests/issues/75), though to my shame it remains unaddressed.
