### ISSUE TITLE
65C02 BIT #imm issue

### ISSUE THREAD

**Issue by sidneycadot** [SingleStepTests/65x02#10]
Hi,

Testcases for "BIT #imm" for at least the WDC 65C02 appear to be incorrect.

For example, this testcase:

{ "name": "89 ab 24", "initial": { "pc": 27641, "s": 20, "a": 235, "x": 178, "y": 150, "p": 235, "ram": [ [27641, 137], [27642, 171], [27643, 36]]}, "final": { "pc": 27643, "s": 20, "a": 235, "x": 178, "y": 150, "p": 233, "ram": [ [27641, 137], [27642, 171], [27643, 36]]}, "cycles": [ [27641, 137, "read"], [27642, 171, "read"]] }

What happens here is that the accumulator contains 0xEB, and it is BIT'ed with immediate value 0xAB.

This should result in the following status bits:
N 1 (copied from bit 7 immediate value)
V 0 (copied from bit 6 of the immediate value)
Z 0 (0xEB & 0xAB is not equal to zero)

However, the testcase shows the V bit set after the operation (P is given as 0xe9 in final).

This is just one example; it appears that many (as high as 75%) of testcases are somehow incorrect.

**Comment by TomHarte** [comment]
Per sources such as [this one](http://www.6502.org/tutorials/65c02opcodes.html) `BIT #imm` differs from the other two `BIT`s in not affecting N or V. It sets Z only.

**Comment by sidneycadot** [comment]
Yes it does. Wow, that's unexpected -- I missed that.

Thanks for the pointer. My mistake.
